minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  - '@caido/quickjs-types'
  - '@caido/server-auth'
  - '@caido/schema-proxy'
  - '@caido/sdk-shared'
  - '@caido-community/quickssrf'
packages:
  - 'packages/*'
  - 'packages/server-auth/examples/*'
  - 'packages/sdk-client/examples/*'
