// This file is auto-generated by @hey-api/openapi-ts

export type AiAssistantContent =
  | (AiText & {
      kind: "text";
    })
  | (AiToolCall & {
      kind: "toolcall";
    })
  | (AiReasoning & {
      kind: "reasoning";
    });

export type AiMessage =
  | {
      content: Array<AiUserContent>;
      role: "user";
    }
  | {
      content: Array<AiAssistantContent>;
      id?: string | null;
      role: "assistant";
    };

export type AiReasoning = {
  id?: string | null;
  reasoning: Array<string>;
  signature?: string | null;
};

export type AiReasoningEffort = "low" | "medium" | "high";

export type AiReasoningEnd = {
  id?: string | null;
  signature?: string | null;
};

export type AiStreamError = {
  error: string;
  message: string;
};

export type AiStreamedAssistantContent =
  | (AiText & {
      kind: "text";
    })
  | (AiToolCall & {
      kind: "tool-call";
    })
  | (AiToolCallDelta & {
      kind: "tool-call-delta";
    })
  | (AiReasoning & {
      kind: "reasoning";
    })
  | (AiReasoningEnd & {
      kind: "reasoning-end";
    })
  | (AiStreamError & {
      kind: "error";
    })
  | {
      kind: "final";
    };

export type AiStructuredOutput = {
  name: string;
  schema: unknown;
  strict?: boolean | null;
};

export type AiText = {
  text: string;
};

export type AiToolCall = {
  additional_params?: unknown;
  call_id: string;
  function: AiToolFunction;
  signature?: string | null;
};

export type AiToolCallDelta = {
  call_id: string;
  content: AiToolCallDeltaContent;
};

export type AiToolCallDeltaContent =
  | {
      kind: "name";
      name: string;
    }
  | {
      delta: string;
      kind: "delta";
    };

export type AiToolDefinition = {
  description: string;
  name: string;
  parameters: unknown;
};

export type AiToolFunction = {
  arguments: unknown;
  name: string;
};

export type AiToolResult = {
  call_id: string;
  content: Array<AiToolResultContent>;
};

export type AiToolResultContent = AiText & {
  kind: "text";
};

export type AiUserContent =
  | (AiText & {
      kind: "text";
    })
  | (AiToolResult & {
      kind: "toolresult";
    });

export type CompletionCapabilities = {
  reasoning: boolean;
  structured_output: boolean;
};

export type CompletionInput = {
  model: CompletionModel;
  request: CompletionRequest;
  stream: boolean;
};

export type CompletionModel = {
  capabilities?: null | CompletionCapabilities;
  name: string;
  provider: CompletionProvider;
};

export type CompletionPayload = {
  choices: Array<AiAssistantContent>;
};

export type CompletionProvider =
  | "openai"
  | "anthropic"
  | "google"
  | "openrouter";

export type CompletionReasoning = {
  effort: AiReasoningEffort;
};

export type CompletionRequest = {
  max_tokens?: number | null;
  messages: Array<AiMessage>;
  reasoning?: null | CompletionReasoning;
  structured_output?: null | AiStructuredOutput;
  system?: string | null;
  temperature?: number | null;
  tools?: Array<AiToolDefinition> | null;
};

export type ErrorResponse = {
  code: number;
  error: string;
  message: string;
};

export type FunctionErrorPayload =
  | {
      kind: "invalid_procedure";
      name: string;
    }
  | {
      expected: string;
      found: string;
      kind: "invalid_output";
    }
  | {
      kind: "thrown";
      message?: string | null;
      stack?: string | null;
    };

export type FunctionInput = {
  args: Array<string>;
  name: string;
};

export type FunctionPayload =
  | {
      kind: "success";
      returns?: string | null;
    }
  | {
      error: FunctionErrorPayload;
      kind: "error";
    };

export type HealthPayload = {
  name: string;
  ready: boolean;
  version: string;
};

export type Id = string;

export type CompletionData = {
  body: CompletionInput;
  path?: never;
  query?: never;
  url: "/ai/completion";
};

export type CompletionErrors = {
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type CompletionError = CompletionErrors[keyof CompletionErrors];

export type CompletionResponses = {
  /**
   * Streaming completion response
   */
  200: CompletionPayload;
};

export type CompletionResponse = CompletionResponses[keyof CompletionResponses];

export type BackupData = {
  body?: never;
  path: {
    backup_id: Id;
  };
  query?: never;
  url: "/backup/{backup_id}";
};

export type BackupErrors = {
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type BackupError = BackupErrors[keyof BackupErrors];

export type BackupResponses = {
  /**
   * Streaming backup file
   */
  200: Blob | File;
};

export type BackupResponse = BackupResponses[keyof BackupResponses];

export type CaCertData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ca.crt";
};

export type CaCertErrors = {
  /**
   * Internal server error
   */
  500: string;
};

export type CaCertError = CaCertErrors[keyof CaCertErrors];

export type CaCertResponses = {
  /**
   * CA certificate
   */
  200: Blob | File;
};

export type CaCertResponse = CaCertResponses[keyof CaCertResponses];

export type DataExportData = {
  body?: never;
  path: {
    export_id: Id;
  };
  query?: never;
  url: "/exports/data/{export_id}";
};

export type DataExportErrors = {
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type DataExportError = DataExportErrors[keyof DataExportErrors];

export type DataExportResponses = {
  /**
   * Streamed data export
   */
  200: unknown;
};

export type LogsExportData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/exports/logs";
};

export type LogsExportErrors = {
  /**
   * Internal server error
   */
  500: string;
};

export type LogsExportError = LogsExportErrors[keyof LogsExportErrors];

export type LogsExportResponses = {
  /**
   * Logs archive
   */
  200: Blob | File;
};

export type LogsExportResponse = LogsExportResponses[keyof LogsExportResponses];

export type GraphqlPlaygroundData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/graphql";
};

export type GraphqlPlaygroundResponses = {
  /**
   * GraphQL playground
   */
  200: unknown;
};

export type GraphqlData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/graphql";
};

export type GraphqlResponses = {
  /**
   * GraphQL request
   */
  200: unknown;
};

export type GraphqlPlaygroundFileData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/graphql/{filename}";
};

export type GraphqlPlaygroundFileResponses = {
  /**
   * GraphQL playground file
   */
  200: unknown;
};

export type HealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthResponses = {
  /**
   * Proxy API health
   */
  200: HealthPayload;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type FunctionData = {
  body: FunctionInput;
  path: {
    plugin_id: Id;
  };
  query?: never;
  url: "/plugin/backend/{plugin_id}/function";
};

export type FunctionErrors = {
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type FunctionError = FunctionErrors[keyof FunctionErrors];

export type FunctionResponses = {
  /**
   * Plugin function call
   */
  200: FunctionPayload;
};

export type FunctionResponse = FunctionResponses[keyof FunctionResponses];

export type GetPluginAssetsFileData = {
  body?: never;
  path: {
    plugin_id: Id;
    file_path: string;
  };
  query?: never;
  url: "/plugin/frontend/{plugin_id}/assets/{file_path}";
};

export type GetPluginAssetsFileErrors = {
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type GetPluginAssetsFileError =
  GetPluginAssetsFileErrors[keyof GetPluginAssetsFileErrors];

export type GetPluginAssetsFileResponses = {
  /**
   * Plugin asset file
   */
  200: unknown;
};

export type GetPluginFileData = {
  body?: never;
  path: {
    plugin_id: Id;
    file_name: string;
  };
  query?: never;
  url: "/plugin/frontend/{plugin_id}/{file_name}";
};

export type GetPluginFileErrors = {
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type GetPluginFileError = GetPluginFileErrors[keyof GetPluginFileErrors];

export type GetPluginFileResponses = {
  /**
   * Plugin file
   */
  200: unknown;
};

export type GraphqlWsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ws/graphql";
};

export type ClientOptions = {
  baseUrl: `${string}://src` | (string & {});
};
