name: Documentation

on:
  push:
    branches:
      - 'main'

env:
  CAIDO_REF: ${{ github.ref }}
  CAIDO_GITHUB_TOKEN: ${{ github.token }}
  CAIDO_DOC_RW_TOKEN: ${{ secrets.CI__DOC__RW }}

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sdk-js
        uses: actions/checkout@v4
        with:
          repository: caido/sdk-js
          ref: ${{ env.CAIDO_REF }}
          path: ./sdk-js
          token: ${{ env.CAIDO_GITHUB_TOKEN }}

      - name: Checkout doc-developer
        uses: actions/checkout@v4
        with:
          repository: caido/doc-developer
          ref: main
          path: ./doc-developer
          token: ${{ env.CAIDO_DOC_RW_TOKEN }}

      - name: Install Mise
        uses: caido/action-mise-action@v3.2.0
        with:
          working_directory: ./sdk-js
          version: ${{ vars.CI__MISE_VERSION }}

      - name: Install Mise
        uses: caido/action-mise-action@v3.2.0
        with:
          working_directory: ./doc-developer
          version: ${{ vars.CI__MISE_VERSION }}

      - name: Install dependencies
        working-directory: ./sdk-js
        run: pnpm install

      - name: Run script
        working-directory: ./doc-developer
        run: pnpm generate:sdk

      - name: Pull Request
        uses: caido/action-pull-request@v6.0.1
        with:
          token: ${{ env.CAIDO_DOC_RW_TOKEN }}
          path: ./doc-developer
          commit-message: Update SDK Documentation
          committer: Caido Bot <dev@caido.io>
          author: Caido Bot <dev@caido.io>
          branch: bot-sdk-update
          delete-branch: true
          base: main
          title: Update SDK Documentation
          body: ''
