name: Documentation

on:
  push:
    branches:
      - 'main'

env:
  CAIDO_NODE_VERSION: 20
  CAIDO_PNPM_VERSION: 9

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CAIDO_NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: ${{ env.CAIDO_PNPM_VERSION }}
          run_install: false

      - name: Checkout sdk-js
        uses: actions/checkout@v4
        with:
          repository: caido/sdk-js
          ref: ${{ env.CAIDO_REF }}
          path: ./sdk-js
          token: ${{ env.CAIDO_GITHUB_TOKEN }}

      - name: Checkout doc-developer
        uses: actions/checkout@v4
        with:
          repository: caido/doc-developper
          ref: main
          path: ./doc-developper
          token: ${{ env.CAIDO_DOC_RW_TOKEN }}

      - name: Run script
        working-directory: ./doc-developer
        run: pnpm generate:sdk

      - name: Pull Request
        uses: caido/action-pull-request@v6.0.1
        with:
          token: ${{ secrets.BOT_SECRET }}
          path: ./doc-developer
          commit-message: Update SDK Documentation
          committer: Caido Bot <dev@caido.io>
          author: Caido Bot <dev@caido.io>
          branch: bot-sdk-update
          delete-branch: true
          base: main
          title: Update SDK Documentation
          body: ''
