name: Validate

on:
  push:
    branches:
      - 'main'
  pull_request:

concurrency:
  group: validate-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate:
    name: 'Validate'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install Mise
        uses: caido/action-mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          version: ${{ vars.CI__MISE_VERSION }}
          experimental: true # Necessary for custom backend plugins

      - name: Install dependencies
        run: pnpm install

      - name: Run validation
        run: mise validate
